default_wallpaper = "images/default_wallpaper.jpg"
default_font = "MS Shell Dlg 2"
default_folder = "text_documents"
default_font_size = "11pt"
default_label_font_size = "11pt"
default_background_color_rgb_code = "255, 255, 255"
default_transparency = "0.5"
default_background_color = f"rgba({default_background_color_rgb_code}, {default_transparency})"